"""açıklama

Revision ID: 57ee9fb25eb9
Revises: 96a2792efc7c
Create Date: 2025-07-09 14:48:02.159689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57ee9fb25eb9'
down_revision: Union[str, Sequence[str], None] = '96a2792efc7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kitaplar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kitaplar',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ad', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('yazar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('yayinevi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('basim_yili', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('kitaplar_pkey'))
    )
    # ### end Alembic commands ###
